# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.49.0"
"rocks-git.nvim" = "2.5.10"
"rocks-config.nvim" = "3.2.0"
"flash.nvim" = "2.1.0"
nvim-treesitter-textobjects = "scm"
"telescope.nvim" = "scm"
"telescope-file-browser.nvim" = "scm"
"todo-comments.nvim" = "1.5.0"
cmp-nvim-lsp = "scm"
"mason.nvim" = "2.2.1"
"mason-lspconfig.nvim" = "2.2.0"
nvim-lspconfig = "2.9.0"
nvim-cmp = "scm"
# neotest = "5.18.0"
# nvim-dap-python = "scm"
# nvim-dap-ui = "4.0.0"
# nvim-dap = "0.10.0"
luarocks = "3.13.0"
tree-sitter-python = "0.0.56"
"nvim-highlight-colors" = "scm"
"tokyonight.nvim" = "4.14.1"
nvim-web-devicons = "0.100"
"lsp_signature.nvim" = "0.3.1"
# "rocks-treesitter.nvim" = "1.3.1"
# neotest-python = "scm"

[config]
colorscheme = 'tokyonight'

[plugins."telescope-live-grep-args.nvim" ]
git = "nvim-telescope/telescope-live-grep-args.nvim"
rev = "v1.1.0"

[plugins."telescope-fzf-native.nvim" ]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "1f08ed60cafc8f6168b72b80be2b2ea149813e55"

[plugins."undotree" ]
git = "mbbill/undotree"
rev = "28f2f54a34baff90ea6f4a735ef1813ad875c743"

[plugins."fugitive" ]
git = "tpope/vim-fugitive"
rev = "v3.7"

[plugins.nerdcommenter ]
git = "preservim/nerdcommenter"
rev = "2.7.0"

[plugins.gitsigns ]
git = "lewis6991/gitsigns.nvim"
rev = "v2.1.0"

[bundles.telescope]
items = [
    "telescope-live-grep-args.nvim",
    "telescope-fzf-native.nvim",
    "telescope.nvim",
    "telescope-file-browser.nvim"
]

[bundles.lsp]
items = [
   "nvim-lspconfig",
   "cmp-nvim-lsp",
   "nvim-cmp",
   "mason.nvim",
   "mason-lspconfig.nvim"
]

# [bundles.neotest]
# items = [
#     "neotest",
#     "nvim-dap-python",
#     "neotest-python",
# ]

# [bundles.dap]
# items = [
#     "nvim-dap",
#     "nvim-dap-ui",
#     "nvim-dap-python",
# ]
